

export const DESCRICAO_DO_CALCULAR =
  'Cruza, agrupa e compara números na bancada de cálculo com SQL de LEITURA (SQLite: SELECT ou WITH, uma instrução só). Tabelas JÁ CARREGADAS: `historico` (uma linha por entidade e dia, últimos 90 dias: entidade_id, entidade_nome, nivel [account|campaign], dia, spend, impressions, reach, frequency, clicks, ctr, cpc, cpm, conversions, conversion_value, roas, cpa) e `normal_da_conta` (metrica, p25, mediana, p75, n). Essas duas só chegam a conta e campanha, e não têm detalhamento nenhum: o recorte que falta (conjunto, anúncio, idade, gênero, posicionamento, dispositivo, semana, mês) você TRAZ com consultarMeta, e cada leitura vira mais uma tabela aqui. Se a tabela que a sua hipótese pede não existe, leia com consultarMeta antes; não desista da pergunta nem responda sem o dado. Use para responder com dado cruzado (semana a semana, por entidade, contra o normal da conta) em vez de estimar de cabeça. Ids são texto. A saída vem capada em 200 linhas: agrupe e filtre. Se a consulta falhar, a resposta traz as tabelas e colunas disponíveis para você corrigir. Em `porque`, diga em até 80 caracteres o que quer descobrir com este cálculo.'

export function descricoesDeTools(investigacao: boolean): {
  gerarRelatorio: string
  buscarMetricasTrafego: string
  proporAcaoMeta: string
  
  entityIdDoProporAcaoMeta: string
  
  statusAtualDoProporAcaoMeta: string
} {
  return {
    statusAtualDoProporAcaoMeta: investigacao
      ? 'OBRIGATÓRIO para pausar/reativar: o campo status (ACTIVE ou PAUSED) que você LEU da entidade em consultarMeta. É o campo status mesmo, NUNCA o effective_status (que devolve CAMPAIGN_PAUSED, WITH_ISSUES e outros, e não serve de foto). É ele que permite desfazer depois, então NUNCA chute: se não leu, leia antes. Sem ele o pedido é recusado.'
      : 'Status atual da entidade (ACTIVE ou PAUSED), se você o tiver lido. Opcional.',
    entityIdDoProporAcaoMeta: investigacao
      ? 'Id da entidade (conjunto/anúncio) — use quando nivel="adset" ou nivel="ad". Passe o id que você leu (no relatório ou em consultarMeta).'
      : 'Id da entidade (conjunto/anúncio) — use quando nivel="adset" ou nivel="ad". O [id] aparece no relatório.',
    gerarRelatorio: investigacao
      ? 'Gera o RELATÓRIO COMPLETO do tráfego no painel (KPIs com variação, gasto por dia, tabela de campanhas, funil real, criativos) lendo o Meta Ads (somente leitura). Use em pergunta de ESTADO: relatório, painel, "como está", "quanto gastei". NÃO encerre com ele uma pergunta de CAUSA ou de DECISÃO ("por que caiu?", "vale escalar?", "o criativo cansou?", "compara os meses"): essas pedem consultarMeta no recorte que separa as suas hipóteses, cruzado na bancada com calcular. O relatório pode ABRIR a investigação, nunca substituí-la. Depois LEIA o resumo e monte 2–4 recomendações com `recomendar`. Esta tool LÊ (somente leitura); para AGIR (pausar/reativar/orçamento), use proporAcaoMeta — com aprovação do dono. Para LANÇAR um criativo aprovado como anúncio, use proporLancarCriativo.'
      : 'Gera o RELATÓRIO COMPLETO do tráfego no painel (KPIs com variação, gasto por dia, tabela de campanhas, funil real, criativos) lendo o Meta Ads (somente leitura). Use SEMPRE que pedirem relatório/painel/"como está". Depois LEIA o resumo e monte 2–4 recomendações com `recomendar`. Esta tool LÊ (somente leitura); para AGIR (pausar/reativar/orçamento), use proporAcaoMeta — com aprovação do dono. Para LANÇAR um criativo aprovado como anúncio, use proporLancarCriativo.',
    buscarMetricasTrafego: investigacao
      ? 'Lê o Meta Ads (somente leitura) e grava as métricas do período. Use ANTES de montar blocos ou recomendar — traz um resumo (gasto/ROAS/CPA/conversões/CTR) pra você diagnosticar. Nível account (conta), campaign, adset ou ad. Você LÊ aqui; para AGIR (pausar/reativar), use proporAcaoMeta — com aprovação do dono. Para LANÇAR um criativo aprovado como anúncio, use proporLancarCriativo. Só proponha ação sobre entidade que você já leu, por qualquer olho (relatório ou consultarMeta).'
      : 'Lê o Meta Ads (somente leitura) e grava as métricas do período. Use ANTES de montar blocos ou recomendar — traz um resumo (gasto/ROAS/CPA/conversões/CTR) pra você diagnosticar. Nível account (conta), campaign, adset ou ad. Você LÊ aqui; para AGIR (pausar/reativar), use proporAcaoMeta — com aprovação do dono. Para LANÇAR um criativo aprovado como anúncio, use proporLancarCriativo.',
    proporAcaoMeta: investigacao
      ? 'PROPÕE (não executa) uma ação de escrita no Meta: PAUSAR, REATIVAR ou ajustar o ORÇAMENTO diário (informe `valor` em reais) de uma campanha, conjunto ou anúncio. Cria uma proposta que o dono aprova em /aprovações — sem aprovação, NADA muda. Só proponha sobre entidade que você já leu, por qualquer olho (relatório ou consultarMeta), e com decisão CLARA. Use `nivel` para especificar o nível (padrão "campaign"): "adset" pausa/reativa um CONJUNTO específico ou ajusta seu orçamento em conta ABO; "ad" pausa/reativa um ANÚNCIO específico (anúncios não têm orçamento próprio). Passe `entityId` com o id que você leu (ou `campaignId` para compat com campanha). Para orçamento, passe também `valor` (novo orçamento diário em R$). IMPORTANTE — AJA: quando o dono pedir pra PAUSAR, REATIVAR ou MUDAR O ORÇAMENTO de uma entidade que você já leu, CHAME esta tool AGORA pra criar a proposta. NUNCA responda com instruções manuais ("abra o Gerenciador, ajuste você mesmo") — você é o gestor que AGE (com aprovação); o dono pediu ação, não um tutorial.'
      : 'PROPÕE (não executa) uma ação de escrita no Meta: PAUSAR, REATIVAR ou ajustar o ORÇAMENTO diário (informe `valor` em reais) de uma campanha, conjunto ou anúncio. Cria uma proposta que o dono aprova em /aprovações — sem aprovação, NADA muda. Só proponha sobre entidade que você LEU (chame gerarRelatorio antes) e com decisão CLARA. Use `nivel` para especificar o nível (padrão "campaign"): "adset" pausa/reativa um CONJUNTO específico ou ajusta seu orçamento em conta ABO; "ad" pausa/reativa um ANÚNCIO específico (anúncios não têm orçamento próprio). Passe `entityId` com o [id] do relatório (ou `campaignId` para compat com campanha). Para orçamento, passe também `valor` (novo orçamento diário em R$). IMPORTANTE — AJA: quando o dono pedir pra PAUSAR, REATIVAR ou MUDAR O ORÇAMENTO de uma entidade que você já leu, CHAME esta tool AGORA pra criar a proposta. NUNCA responda com instruções manuais ("abra o Gerenciador, ajuste você mesmo") — você é o gestor que AGE (com aprovação); o dono pediu ação, não um tutorial.',
  }
}
